<?php

/**
 * Implementation of hook_uninstall().
 */
function uc_payflowpro_ec_uninstall() {
  variable_del('uc_payflowpro_ec_reqconfirmed_addr');
  variable_del('uc_payflowpro_ec_review_comment');
  variable_del('uc_payflowpro_ec_review_company');
  variable_del('uc_payflowpro_ec_review_phone');
  variable_del('uc_payflowpro_ec_review_shipping');
  variable_del('uc_payment_method_payflowpro_ec_checkout'); // TODO: used?
}
